### ISSUE TITLE
مشکل عجیب بعد از نصب بستهٔ laravel-persian-slug

### ISSUE THREAD

**Issue by mrostd** [pishran/laravel-persian-slug#10]
وقت به‌خیر.
بعد از نصب بستهٔ laravel-persian-slug مشکل خیلی عجیبی (حداقل روی پروژهٔ من) به‌وجود می‌آد.
من پروژه‌م در حالت عادی به‌خوبی کار می‌کنه، چیز پیچیده‌ای نداره، صرفا یه صفحهٔ ایجاد دسته‌بندیه، اما به محض نصب بستهٔ شما، اتفاق عجیبی رخ می‌ده که اینجا شرح می‌دم.
من چنین مسیری تو پروژهٔ خودم دارم:

```php
use App\Http\Controllers\Admin\Content\CategoryController as ContentCategoryController;

Route::prefix('admin')->group(function () {
    Route::get('/', [AdminDashboardController::class, 'index'])->name('admin.home');
    Route::prefix('content')->group(function () {
        Route::prefix('category')->controller(ContentCategoryController::class)->group(function () {
            Route::get('/', 'index')->name('admin.content.category.index');
            Route::get('/create', 'create')->name('admin.content.category.create');
            Route::post('/store', 'store')->name('admin.content.category.store');
            Route::get('/edit/{postCategory}', 'edit')->name('admin.content.category.edit');
            Route::put('/update/{postCategory}', 'update')->name('admin.content.category.update');
            Route::delete('/destroy/{postCategory}', 'destroy')->name('admin.content.category.destroy');
            Route::get('/status/{postCategory}', 'status')->name('admin.content.category.status');
        });
    });
});
```
هیچ چیز عجیبی در این رابطه وجود نداره، همچنین در ContentCategoryController هم این متدها وجود دارند:

```php
    public function index()
    {
        $postCategories = PostCategory::orderBy('created_at', 'desc')->simplePaginate(15);
        return view('admin.content.category.index', compact('postCategories'));
    }
    public function create()
    {
        return view('admin.content.category.create');
    }
    public function store(StorePostCategoryRequest $request)
    {
        $inputs = $request->all();
        $inputs['image'] = 'image';
        $postCategories = PostCategory::create($inputs);
        return redirect()->route('admin.content.category.index')->with('swal-success', 'دسته بندی جدید شما با موفقیت ثبت شد');
    }
    public function edit(PostCategory $postCategory)
    {
        return view('admin.content.category.edit', compact('postCategory'));
    }
    public function update(UpdatePostCategoryRequest $request, PostCategory $postCategory)
    {
        $inputs = $request->all();
        $inputs['image'] = 'image';
        $postCategory->update($inputs);
        return redirect()->route('admin.content.category.index')->with('swal-success', 'دسته بندی جدید شما با موفقیت ویرایش شد');
    }
    public function destroy(PostCategory $postCategory)
    {
        $result = $postCategory->delete();
        return redirect()->route('admin.content.category.index')->with('swal-success', 'دسته بندی شما با موفقیت حذف شد');
    }
```

هنگامی که در مدل از بستهٔ laravel-sluggable استفاده می‌شه، عملیات store به‌خوبی انجام می‌شه، همچنین با کلیک بر روی دکمه‌های ویرایش و حذف، به راحتی به صفحهٔ edit هدایت می‌شم و با زدن دکمهٔ حذف، رکورد مورد نظر حذف می‌شه.
اما زمانی که از laravel-persian-slug استفاده می‌شه، گرچه عملیات store کردن به‌خوبی هرچه تمام انجام می‌شه و اسلاگ‌ها به فارسی ساخته می‌شه، اما به محض کلیک روی دکمهٔ ویرایش و حتی حذف، وارد اون روت می‌شم اما صفحهٔ ۴۰۴ می‌بینم.
![image](https://github.com/pishran/laravel-persian-slug/assets/53259265/b4dea0ad-d1c4-4e86-b3e5-9a1b89a0bcf4)
این اتفاق دقیقا زمانی که روی «حذف» هم کلیک می‌کنم می‌افته:

![image](https://github.com/pishran/laravel-persian-slug/assets/53259265/d8b8ff7f-4ccb-4a39-8a54-3512a697b87d)
[Screencast from 2023-09-10 16-24-26.webm](https://github.com/pishran/laravel-persian-slug/assets/53259265/a83af356-4776-4939-831a-702d17d36822)

**Comment by mrostd** [comment]
از اونجایی که توضیح این که مشکل چیه با متن خیلی سخت بود، یه Screencast گذاشتم که بهتر منظورم رو برسونم.

**Comment by FaridAghili** [comment]
متوجه مشکلتون شدم.

این پکیج یه تفاوتی با پکیج laravel-sluggable داره اونم اینه که getRouteKeyName رو هم برای Model تنظیم می‌کنه. می‌تونین تو لینک زیر ببینین:
https://github.com/pishran/laravel-persian-slug/blob/2ed3b9cbf77131d0044a74da82003be12f390f8a/src/HasPersianSlug.php#L41

بنابراین، لینک مدل شما به جای:
`http://127.0.0.1:8000/admin/content/category/edit/20`
میشه:
`http://127.0.0.1:8000/admin/content/category/edit/slug-instread-of-id`

تو سیستم مدیریت محتواتون اونجایی که دارید لینک دکمه‌های ویرایش و حذف و ... رو می‌سازین، به جای id از slug استفاده کنین تا لینک صحیح تولید بشه.

یا اینکه می‌تونین تو مدل متدی که گفتم رو overwrite کنین تا با id کار کنه:

```php
public function getRouteKeyName()
{
    return $this->getKeyName();
}
```

**Comment by mrostd** [comment]
خیلی خیلی خیلی ممنونم!
به نظرم اگه براتون مقدور بود و زمانش رو داشتید این نکته رو تو readme ذکر کنید، اگه کسی آشنا نباشه کمی سردرگم می‌شه.
