### ISSUE TITLE
مشکل با سافت‌دیلیت

### ISSUE THREAD

**Issue by mrostd** [pishran/laravel-persian-slug#11]
وقت به‌خیر، توی بستهٔ eloquent-sluggable آپشنی وجود داشت تا هنگام سافت دیلیت مشکلی برامون به‌وجود نیاد:
```php
    /**
     * Should we include the trashed items when generating a unique slug?
     * This only applies if the softDelete property is set for the Eloquent model.
     * If set to "false", then a new slug could duplicate one that exists on a trashed model.
     * If set to "true", then uniqueness is enforced across trashed and existing models.
     */

    'includeTrashed' => true,
```
 اما اینجا دستوری نمی‌بینم جایی که اجازه بده که فایل sluggable.php رو publish کنم، خواستم بپرسم چطور می‌تونم این کار رو اینجا انجام بدم؟

**Comment by FaridAghili** [comment]
پکیج spatie/laravel-sluggable رو چک کردم، کلا فایل config برای پابلیش ندیدم توش.

در مورد سافت دیلیت، تو کد زیر می‌تونین ببینین، اگه Model شما SoftDeletes رو use کرده باشه، پکیج بصورت خودکار رکوردهای دیلیت شده رو هم در تولید slug یکتا لحاظ می‌کنه.

https://github.com/spatie/laravel-sluggable/blob/18bbcb0a18e99a751228ca3ff13ca049bf3f93f4/src/HasSlug.php#L153

اون قسمت `'includeTrashed' => true,` رو من نتونستم تو پکیج اصلی پیدا کنم کجاست.

**Comment by mrostd** [comment]
> پکیج spatie/laravel-sluggable رو چک کردم، کلا فایل config برای پابلیش ندیدم توش.
> 
> در مورد سافت دیلیت، تو کد زیر می‌تونین ببینین، اگه Model شما SoftDeletes رو use کرده باشه، پکیج بصورت خودکار رکوردهای دیلیت شده رو هم در تولید slug یکتا لحاظ می‌کنه.
> 
> https://github.com/spatie/laravel-sluggable/blob/18bbcb0a18e99a751228ca3ff13ca049bf3f93f4/src/HasSlug.php#L153
> 
> اون قسمت `'includeTrashed' => true,` رو من نتونستم تو پکیج اصلی پیدا کنم کجاست.

یعنی به‌صورت خودکار تشخیص می‌ده؟
ممنونم!
بله تو پکیج شما یا spatie/laravel-sluggable وجود نداشت این‌ها که گفتم، همونطور که بالاتر هم نوشتم توی eloquent-sluggable وجود داره و دنبال معادلش تو اینجا بودم.
با تشکر از پاسخگویی شما.
