### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by iranpourX** [pishran/laravel-persian-slug#2]
سلام
موقع نصب یه نوتیس میده

_Deprecation Notice: Class Pishran\LaravelPersianSlug\HasPersianSlug located in C:/Users/Ali/Desktop/thesaurus/vendor/pishran/laravel-persian-slug/src\HasPersianString.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201_

**Comment by FaridAghili** [comment]
سلام

بله حق با شماست
مربوط به اینه که لود خودکار این پکیج در نسخه ۲ کمپوسر پشتیبانی نمی‌شه

هنوز تا انتشار نسخه ۲ کمپوسر زمان داریم
به زودی این مشکل رو برطرف می‌کنم

**Comment by FaridAghili** [comment]
Fixed in [v1.4](https://github.com/pishran/laravel-persian-slug/releases/tag/v1.4).
