### ISSUE TITLE
تبدیل نشدن حروف به فارسی

### ISSUE THREAD

**Issue by sadeqsafaeian** [pishran/laravel-persian-slug#4]
در ورژن 8 لاراول این پکیج به درستی کار نمیکنه حروف فارسی رو  به همان صورت ولی به شکل فینگلش ذخیره میکنه
راه حل چیه؟

**Comment by FaridAghili** [comment]
روی لاراول ۷ و ۸ و همینطور پی‌اچ‌پی ۷ و ۸ تست کردم، در تمام تست‌ها هم برای عبارات انگلیسی و هم فارسی به درستی عمل می‌کرد و مشکلی که گفتید رو نداشت.

لطفا یک ریپازیتوری که مشکلی که توضیح دادید رو داشته باشه ایجاد کنید تا بتونم از روی اون تست و بررسی کنم چون در بررسی‌های خودم نتونستم مشکل شما رو ایجاد کنم.
