### ISSUE TITLE
مشکل در ارسال slug فارسی

### ISSUE THREAD

**Issue by matinwd** [pishran/laravel-persian-slug#5]
با سلام و وقت بخیر
اسلاگ فارسی به این شکل ذخیره میشه:

کوین-اسپیسی-دستگیر-شد-8

ولی وقتی توی مرورگر میخوام بگیرمش این شکلی میشه و وقتی میفرستمش سمت سرور نمیتونم باهاش کار کنم

%DA%A9%D9%88%DB%8C%D9%86-%D8%A7%D8%B3%D9%BE%DB%8C%D8%B3%DB%8C-%D8%AF%D8%B3%D8%AA%DA%AF%DB%8C%D8%B1-%D8%B4%D8%AF-8

ممنون میشم راهنمایی کنید

**Comment by FaridAghili** [comment]
سلام
این موردی که گفتین ارتباطی با این پکیج نداره

بطور کلی وقتی یک لینک فارسی رو از مرورگر (مثلا گوگل کروم) کپی می‌کنید، بصورت خودکار به شکل انکد شده کپی می‌شه
به خاطره همین وقتی لینک رو بعد از کپی جای دیگه پیست می‌کنید اون شکلی دیده میشه

با استفاده از تابع urldecode در پی‌اچ‌پی و یا سایت زیر می‌تونین لینک‌های انکد شده رو دیکد کنید:
https://www.urldecoder.org/
