### ISSUE TITLE
پشتیبانی از لاراول 10

### ISSUE THREAD

**Issue by mrostd** [pishran/laravel-persian-slug#9]
وقت به‌خیر، برنامه‌ای برای پشتیبانی بسته از لاراول ۱۰ دارید؟

**Comment by FaridAghili** [comment]
روی آخرین نسخه لاراول و آخرین نسخه PHP قابل استفاده‌ست، مشکلی نداره.

الان روی Laravel 10.22.0 و PHP 8.2.10 نصب و تست کردم، اوکیه.
